### ISSUE TITLE
Write a summary of our understanding of the app

### ISSUE THREAD

**Issue by aleiscoding** [estebansanch/DeviceLoanMigration#1]

**Comment by DavidVelazquez584** [comment]
Link for the drive document of the summary: https://docs.google.com/document/d/1FaETIygpTjMnKbnUwtenxn64Ap6zFun6JgFmxYoPCr8/edit?usp=sharing

**Comment by JoseZurdo** [comment]
Cannot open the drive. Please provide access to Harold and I in order the check your progress.

**Comment by estebansanch** [comment]
https://docs.google.com/document/d/1FaETIygpTjMnKbnUwtenxn64Ap6zFun6JgFmxYoPCr8/edit?usp=drivesdk
