### ISSUE TITLE
Finish Audit

### ISSUE THREAD

**Issue by estebansanch** [estebansanch/DeviceLoanMigration#13]

**Comment by estebansanch** [comment]
- [ ] Change Management

- [ ] Environment Separation

- [ ] Access Management

**Comment by estebansanch** [comment]
https://docs.google.com/spreadsheets/d/1W5Oa01_RpnNhEQSJf8jwN-UHfVtyjBmn/edit?usp=sharing&ouid=106721719080726198479&rtpof=true&sd=true

**Comment by JoseZurdo** [comment]
I´ve checked your audit file. Just an observation, in the Mission/Vision doc, there are some translation mistakes in the Values section.

**Comment by JoseZurdo** [comment]
[Audit File RanchoDev.xlsx](https://github.com/estebansanch/DeviceLoanMigration/files/8247697/Audit.File.RanchoDev.xlsx)
This is the audit file with comments by me and Alec Carbo. If requested, provide new evidence or correct them.
