### ISSUE TITLE
Functional and Nonfunctional Requirements Infographic

### ISSUE THREAD

**Issue by aleiscoding** [estebansanch/DeviceLoanMigration#29]

**Comment by aleiscoding** [comment]
Infographic link: https://www.canva.com/design/DAE6WIXDNHc/gyaMsJ6nCOCuVXydIleXrQ/view?utm_content=DAE6WIXDNHc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by JoseZurdo** [comment]
I like it, move it to done. I would also suggest to take into account Scalability or Data Integrity as non functional requirements =)
