### ISSUE TITLE
Tener entrevista con socio IBM

### ISSUE THREAD

**Issue by estebansanch** [estebansanch/DeviceLoanMigration#6]

**Comment by estebansanch** [comment]
Interview is on Tuesday, March 1st at 11 am. Suggest all team members form a list of questions for tomorrow.

**Comment by JoseZurdo** [comment]
If there are no questions, you can move it to Done.

**Comment by estebansanch** [comment]
https://drive.google.com/file/d/17lSOH6AF-3ZoQbGYxP0hO4ZehCmIHMVX/view?usp=sharing
